name: Build and deploy

on:
  push:
    branches:
      - production
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PNPM
        run: npm install --global corepack@latest

      - name: Install Packages
        run: pnpm i

      - name: Bundle
        run: pnpm run buld
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: production
          folder: dist